[global]
type=global

[transport-udp-nat]
type=transport
protocol=udp
bind=0.0.0.0:5060


[1002]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
aors=1002
auth=1002-auth
transport=transport-udp-nat
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes


[1002-auth]
type=auth
auth_type=userpass
password=1002
username=1002

[1002]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60